In [10]:
import sqlite3
import joblib
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [11]:
conn = sqlite3.connect("../database/credit_risk.db")

print("Database Connected!")

Database Connected!

In [12]:
df = pd.read_sql(
    "SELECT * FROM credit_data",
    conn
)

print(df.shape)

display(df.head())

(30000, 25)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [13]:
TARGET_COLUMN = "default payment next month"

# Remove ID and target
X = df.drop(
    columns=[
        "ID",
        TARGET_COLUMN
    ]
)

y = df[TARGET_COLUMN]

print("Features:", X.shape)
print("Target:", y.shape)

Features: (30000, 23)
Target: (30000,)

In [14]:
joblib.dump(
    list(X.columns),
    "../models/feature_columns.pkl"
)

print("Feature Columns Saved!")

Feature Columns Saved!

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(24000, 23)
(6000, 23)

In [16]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

print("Scaling Complete!")

Scaling Complete!

In [17]:
joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler Saved!")

Scaler Saved!

In [18]:
X_train_scaled.to_csv(
    "../data/processed/X_train.csv",
    index=False
)

X_test_scaled.to_csv(
    "../data/processed/X_test.csv",
    index=False
)

y_train.to_csv(
    "../data/processed/y_train.csv",
    index=False
)

y_test.to_csv(
    "../data/processed/y_test.csv",
    index=False
)

print("Processed datasets saved!")

Processed datasets saved!

In [19]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(
    X_train_scaled,
    y_train
)

print("Model Trained!")

Model Trained!

In [20]:
joblib.dump(
    model,
    "../models/logistic_regression.pkl"
)

print("Model Saved!")

Model Saved!

In [21]:
print("Training Features:")
display(X_train_scaled.head())

print("\nFeature Names:")
print(X_train_scaled.columns.tolist())

Training Features:

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
22788,-0.056866,0.80844,0.184523,0.856739,-0.264558,1.793311,1.780193,2.652046,1.911811,0.240260,...,1.778869,1.891679,2.020839,2.096346,0.580657,-0.290332,-0.297820,0.086961,0.500397,0.048745
29006,-0.134081,0.80844,-1.077532,0.856739,-0.155804,0.902944,-0.722324,-0.697642,-1.530826,-1.537252,...,-0.685090,-0.673845,-0.662488,-0.652126,-0.344969,-0.290332,-0.297820,-0.318075,-0.316978,-0.292992
16950,-1.215090,-1.23695,0.184523,-1.059367,1.584260,0.902944,1.780193,0.139780,0.190493,0.240260,...,-0.561615,-0.547887,-0.526789,-0.510492,-0.348128,-0.227081,-0.233069,-0.298554,-0.296710,-0.236970
22280,0.406423,0.80844,-1.077532,0.856739,-0.699574,0.012576,0.111849,0.139780,0.190493,0.240260,...,2.460102,2.738001,1.509166,1.613118,0.215287,0.154056,0.152526,0.000642,0.008643,0.043143
11346,1.101358,0.80844,-1.077532,0.856739,-0.373312,0.902944,-1.556496,-0.697642,0.190493,0.240260,...,-0.680324,-0.668755,-0.666365,-0.656089,-0.348251,-0.274236,-0.297820,-0.318075,-0.316978,-0.225765

Feature Names:
['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']